ezcontent_preview.ezcontent_preview.*:
  type: config_entity
  label: 'EZContent config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: string
      label: 'URL'
    newtab:
      type: boolean
      label: 'New Tab'
    token_time:
      type: string
      label: 'Token Time'
    content_entity:
      type: list_string
      label: 'Content Entity'
